apiVersion: v1
kind: Namespace
metadata:
  name: polaris
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: average-cpu-utilization
  namespace: polaris
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # ClusterRoles are not namespaced
  name: average-cpu-utilization
rules:
  # Allow reading all SLO mappings
  # - apiGroups:
  #   - slo.polaris-slo-cloud.github.io
  #   resources:
  #   - "*"
  #   verbs:
  #   - get
  #   - watch
  #   - list

  # Allow reading all Deployments, StatefulSets, ReplicaSets, and DaemonSets
  - apiGroups:
      - 'apps'
    resources:
      - deployments
      - statefulsets
      - replicasets
      - daemonsets
    verbs:
      - get

  # Allow reading supported SLO mappings
  - apiGroups:
      - slo.polaris-slo-cloud.github.io
    resources:
      - cpuutilizationslomappings
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - slo.polaris-slo-cloud.github.io
    resources:
      - cpuutilizationslomappings/status
    verbs:
      - get

  # Allow writing all elasticity strategies
  - apiGroups:
      - elasticity.polaris-slo-cloud.github.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  # Allow writing all metric mappings.
  - apiGroups:
      - metrics.polaris-slo-cloud.github.io
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
# Optionally, we could create a RoleBinding and to scope the permissions to a specific namespace
metadata:
  name: control-cpuutilizationslomappings-slos
subjects:
  - kind: ServiceAccount
    name: average-cpu-utilization
    namespace: polaris
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: average-cpu-utilization
